In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00471/Data_for_UCI_named.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stab    10000 non-null  float64
 13  stabf   10000 non-null  object 
dtypes: float64(13), object(1)
memory usage: 1.1+ MB


In [ ]:
df

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4      stab     stabf  
0    -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1    -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2    -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3    -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4    -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable  
...        ...       ...       ...       ...       ...       ...       ...  
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  0.023892  unstable  
9996 -1.733414  0.502079  0.567242  0.285880  0.366120 -0.025803    stable  
9997 -1.975373  0.487838  0.986505  0.149286  0.145984 -0.031810    stable  
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  0.037789  unstable  
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  0.045263  unstable  

[10000 rows x 14 columns]

In [ ]:
df.isna().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [ ]:
print(df)

          tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4      sta

In [ ]:
df.shape

(10000, 14)

In [ ]:
df.dtypes

tau1     float64
tau2     float64
tau3     float64
tau4     float64
p1       float64
p2       float64
p3       float64
p4       float64
g1       float64
g2       float64
g3       float64
g4       float64
stab     float64
stabf     object
dtype: object

In [ ]:
df.describe()

tau1          tau2          tau3          tau4            p1  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean       5.250000      5.250001      5.250004      5.249997      3.750000   
std        2.742548      2.742549      2.742549      2.742556      0.752160   
min        0.500793      0.500141      0.500788      0.500473      1.582590   
25%        2.874892      2.875140      2.875522      2.874950      3.218300   
50%        5.250004      5.249981      5.249979      5.249734      3.751025   
75%        7.624690      7.624893      7.624948      7.624838      4.282420   
max        9.999469      9.999837      9.999450      9.999443      5.864418   

                 p2            p3            p4            g1            g2  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean      -1.250000     -1.250000     -1.250000      0.525000      0.525000   
std        0.433035      0.433035      0.433035      0.274256      0.274255   
min       -1.999891     -1.999945     -1.999926      0.050009      0.050053   
25%       -1.624901     -1.625025     -1.624960      0.287521      0.287552   
50%       -1.249966     -1.249974     -1.250007      0.525009      0.525003   
75%       -0.874977     -0.875043     -0.875065      0.762435      0.762490   
max       -0.500108     -0.500072     -0.500025      0.999937      0.999944   

                 g3            g4          stab  
count  10000.000000  10000.000000  10000.000000  
mean       0.525000      0.525000      0.015731  
std        0.274255      0.274255      0.036919  
min        0.050054      0.050028     -0.080760  
25%        0.287514      0.287494     -0.015557  
50%        0.525015      0.525002      0.017142  
75%        0.762440      0.762433      0.044878  
max        0.999982      0.999930      0.109403

check for distribution of target variable


In [ ]:
df['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [ ]:
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [ ]:
df.drop('stab', axis=1, inplace= True)


In [ ]:
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  unstable

In [ ]:
x = df.drop('stabf', axis=1)
y = df['stabf']

**splitting** **the** **data** **set** in to training and testing set with 80-20 train-test split 

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state= 1)

**Scaling** **dataset** **using** **Standard** **scaler**

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
train_df= scaler.fit_transform(x_train)
train_df = pd.DataFrame(train_df, columns=x_train.columns)

In [ ]:
test_df = scaler.fit_transform(x_test)
test_df = pd.DataFrame(test_df, columns=x_test.columns )

In [ ]:
train_df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  0.367327 -0.986042  0.650447  1.547527 -0.291490  0.061535  1.293862   
1 -0.064659  0.089437  1.035079 -1.641494  0.619865 -0.067235 -1.502925   
2 -1.467850  1.298418 -0.502536  1.166046 -0.180521  0.490603  0.682560   
3  0.820081  0.529920  1.299657 -1.141975 -0.812854 -0.763632  1.521579   
4  0.665424 -1.425627  0.312300  0.919137 -1.614296  0.760315  1.422019   

         p4        g1        g2        g3        g4  
0 -0.845074  0.160918  0.339859  0.585568  0.492239  
1  0.486613 -0.293143 -1.558488  1.429649 -1.443521  
2 -0.855302  1.399350  1.451534 -1.045743  0.492489  
3  0.658780 -0.958319  1.361958  1.604140  0.275303  
4  0.639243  1.676895  0.695660  1.137504 -1.312575

In [ ]:
test_df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  0.592163 -0.420565  1.472472  1.093036  0.426786 -1.504594 -0.792677   
1  0.199183  0.364543 -0.190076 -0.518473 -0.229402 -1.071766  0.427103   
2 -1.086035 -0.321834 -0.873505  0.011761 -0.977094  0.094896  0.813041   
3 -0.087014 -1.113357  0.361518 -1.684316  0.792280 -1.649041  0.410662   
4  0.873004  1.425833  0.080476  1.681022 -0.154247 -0.024315 -0.197525   

         p4        g1        g2        g3        g4  
0  1.600201 -0.925703  1.175287 -1.492644  1.086291  
1  1.052337 -1.655910 -0.395949  1.412703  1.227535  
2  0.751381  1.450284 -1.444370  0.654216 -1.679799  
3 -0.084473  0.066085 -1.679450 -0.349573  1.057439  
4  0.485988  0.119716 -1.475773  0.957057 -0.817608

**Random** **forest** **with** **scikit** **learn**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
classifier = RandomForestClassifier(random_state =1)

In [ ]:
classifier.fit(train_df, y_train)

RandomForestClassifier(random_state=1)

In [ ]:
y_pred_RF= classifier.predict(test_df)

In [ ]:
# import metrics used to evaluate performance  of classifiaction models
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix

In [ ]:
accuracy = accuracy_score(y_test, y_pred_RF)

In [ ]:
print (f"Accuracy: {round(accuracy, 4)}")

Accuracy: 0.928


In [ ]:
# Confusion matrix 
cfn_matrix_RF = confusion_matrix(y_true = y_test, y_pred= y_pred_RF)


In [ ]:
print(cfn_matrix_RF)

[[ 624   88]
 [  56 1232]]


**For Extra Tree Classifier**

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier 

In [ ]:
EXTC = ExtraTreesClassifier(random_state=1)

In [ ]:
EXTC.fit(train_df, y_train)

ExtraTreesClassifier(random_state=1)

In [ ]:
y_pred_EXTC = EXTC.predict(test_df)

In [ ]:
print(y_pred_EXTC)

['unstable' 'unstable' 'stable' ... 'stable' 'unstable' 'unstable']


In [ ]:
#Confusion Matrix for Extra Tree Classifier
cfn_matrix_EXTC = confusion_matrix(y_true=y_test, y_pred= y_pred_EXTC)

In [ ]:
print(cfn_matrix_EXTC)

[[ 602  110]
 [  38 1250]]


In [ ]:
#Accuracy score for Extra Trees Classification
accuracy = accuracy_score( y_true=y_test, y_pred=y_pred_EXTC)

In [ ]:
print(f"Accuracy: {round(accuracy,4)}")

Accuracy: 0.926


**XGBoost** **to** **train** **an** **Extreme** **Boosting** **Model** 

In [ ]:
import xgboost

In [ ]:
from xgboost import XGBClassifier

In [ ]:
xgb = XGBClassifier (random_state=1)

In [ ]:
xgb.fit(train_df, y_train)

XGBClassifier(random_state=1)

In [ ]:
y_pred_XGB = xgb.predict(test_df)

In [ ]:
print(y_pred_XGB)

['unstable' 'unstable' 'stable' ... 'stable' 'unstable' 'unstable']


In [ ]:
#confusion matrix for xgboost
cfn_matrix_xgb = confusion_matrix(y_true=y_test, y_pred= y_pred_XGB)

In [ ]:
print(cfn_matrix_xgb)

[[ 599  113]
 [  49 1239]]


In [ ]:
#Accuracy on test set for xgboost 
accuracy = accuracy_score(y_test, y_pred_XGB)

In [ ]:
print (f"Accuracy: {round(accuracy,4)}")

Accuracy: 0.919


**LIght GBM to train a light gradient boosting model**

In [ ]:
import lightgbm as lgb

In [ ]:
lgb_classifier= lgb.LGBMClassifier(random_state=1)

In [ ]:
lgb_classifier.fit(train_df, y_train)

LGBMClassifier(random_state=1)

In [ ]:
y_pred_lgb = lgb_classifier.predict(test_df)

In [ ]:
print(y_pred_lgb)

['unstable' 'unstable' 'stable' ... 'stable' 'unstable' 'unstable']


In [ ]:
# confusion matrix for LightGBM
cfn_matrix_lgb = confusion_matrix(y_test, y_pred_lgb)

In [ ]:
print(cfn_matrix_lgb)

[[ 635   77]
 [  52 1236]]


In [ ]:
#Accuracy score for light gbm

In [ ]:
accuracy = accuracy_score(y_test, y_pred_lgb)

In [ ]:
print (f"Accuracy: {round(accuracy,4)}")

Accuracy: 0.9355


Tuning parameters

In [ ]:
n_estimators = [50,100,300,500,1000] 
min_samples_split = [2,3,5,7,9] 
min_samples_leaf = [1,2,4,6,8] 
max_features = ['auto','sqrt','log2',None] 
hyperparameter_grid = {'n_estimators':n_estimators,'min_samples_leaf':min_samples_leaf,'min_samples_split':min_samples_split,
'max_features':max_features}

**Randomized CV search**

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
search = RandomizedSearchCV(estimator = EXTC, param_distributions=hyperparameter_grid,random_state=1)
search = search.fit(train_df, y_train)


In [ ]:
search.best_params_

**New **Extra** **Trees** **Classifier**
 **

In [ ]:
n_classifier = ExtraTreesClassifier(random_state=1,n_estimators = 1000,
                                       min_samples_leaf= 8,max_features=None,
                                       min_samples_split=2)
n_classifier.fit(train_df, y_train)
pred_new = n_classifier.predict(test_df)

In [ ]:
accuracy = accuracy_score(y_test,pred_new)
print(f"Accuracy: {round(accuracy,4)}")

**Feature Importance**

In [ ]:
feat_imp = search.best_estimator_.feature_importances_
feat_imp

In [ ]:
sorted(zip(feat_imp,x))

In [ ]:
max(sorted(zip(feat_imp,x)))

In [ ]:
min(sorted(zip(feat_imp,x)))